apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: letsencrypt-prod
 namespace: cc-dev
spec:
 acme:
  server: https://acme-v02.api.letsencrypt.org/directory
  email: stuart.mcg@hotmail.co.uk
  privateKeySecretRef:
   name: letsencrypt-prod
  solvers:
  - http01:
     ingress:
      class: nginx