name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
     - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build interface/. --file interface/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/counter-build:testpush
    - uses: docker/login-action@v1
      name: login
      with:
        username:  ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/counter-build:testpush
    
