name: Docker Image CI

on:
  push:
    tags:
     - 'v*'
     
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get version
      id: get_version
      uses: battila7/get-version-action@v2.2.1
    - name: Build the Docker image
      run: docker build interface/. --file interface/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/counter:${{ steps.get_version.outputs.version }}
    - uses: docker/login-action@v1
      name: login
      with:
        username:  ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/counter:${{ steps.get_version.outputs.version }}
    
